### ISSUE TITLE
Symbol flickers on state change

### ISSUE THREAD

**Issue by adewalegeorge** [thierrymichel/vue-svg-sprite#11]
Is this due to symbol being redrawn each time the state gets updated?
It sure feels like a bug

**Comment by SecretKeeper** [comment]
same here

**Comment by SecretKeeper** [comment]
@adewalegeorge , @thierrymichel  do you know how to use symbols on CSS Background?

**Comment by thierrymichel** [comment]
Hi @ourfamilygithub,

Any link or repo to see/reproduce this issue?
Never experienced this behaviour…

For SVG symbol and CSS background, you can use [fragment identifier](https://css-tricks.com/svg-fragment-identifiers-work/).

Cheers

**Comment by pieterjanmaes** [comment]
I'm having the same issue on Google Chrome & Safari when the sprite is bigger dan 10kb. No issues on FireFox. Every state change the .svg file is loaded, always with a status of 304.

**Comment by pieterjanmaes** [comment]
Never mind, I found the issue. Had a limit of 10kb in the webpack config rules, make it higher or delete it solved the problem.

`{
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]'),
        },
      },`
