### ISSUE TITLE
TypeSscript compatibility

### ISSUE THREAD

**Issue by demiro** [thierrymichel/vue-svg-sprite#12]
Could you please make it typescript compatible?

I am getting this error when using VUE in TS

```
ERROR in C:/DEVELOPMENT/xx-vue/src/App.vue
42:23 Could not find a declaration file for module 'vue-svg-sprite'. C:/DEVELOPMENT/xx-vue/node_modules/vue-svg-sprite/index.js' implicitly has an 'any' type.
  Try `npm install @types/vue-svg-sprite` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-svg-sprite';`
```

**Comment by thierrymichel** [comment]
@demiro will try to play with TypeScript definitions this week-end.
As I have no big experience with TS, any help is welcome…

**Comment by thierrymichel** [comment]
Hi @demiro,

Finally had some time to move to TypeScript!
See https://github.com/thierrymichel/vue-svg-sprite/blob/master/CHANGELOG.md#130-24032019
