### ISSUE TITLE
xlink:href deprecated

### ISSUE THREAD

**Issue by valjar** [thierrymichel/vue-svg-sprite#13]
Since attribute xlink:href is deprecated it would be useful to change the code output too something similar to this:

`<svg viewBox="0 0 24 24" width="24" height="24" role="presentation" class="icon--inline">
  <use xmlns:xlink="http://www.w3.org/1999/xlink" 
xlink:href="/assets/svg/sprite.svg#icons-dashboard"
href="/assets/svg/sprite.svg#icons-dashboard"></use>
</svg>`

So this way we would be using href element for new browsers and we would also have backward compatibility for older browsers. What do you think?

Best regards,

**Comment by thierrymichel** [comment]
@valjar thanks for your suggestion 👍 .
I've just released a new version with `href` attribute!
See https://github.com/thierrymichel/vue-svg-sprite/blob/master/CHANGELOG.md#130-24032019

**Comment by valjar** [comment]
That was fast! Thank you 😊
