### ISSUE TITLE
Weird issue 

### ISSUE THREAD

**Issue by smitray** [thierrymichel/vue-svg-sprite#2]
Hi there,
I'm facing an issue. I've followed the setup you mentioned but unfortunately my svg file down't get loaded. Even the class isn't showing either. But when I'm using require then the file gets loaded yet the class isn't working.

```
import Vue from 'vue';
import svgSprite from 'vue-svg-sprite';
import {
  ContainerComponent,
  router,
  store,
  blockIntro,
  blockGrid
} from 'shared';

Vue.component('block-intro', blockIntro);
Vue.component('block-grid', blockGrid);

Vue.use(svgSprite, {
  url: require('./assets/img/icons.svg'), //eslint-disable-line
  class: 'icon'
});

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(ContainerComponent)
});
```
I'm using webpack and Vue2. Also the following line is throwing error too.

```
<svg v-svg="icons-dashboard"></svg>
```

**Comment by thierrymichel** [comment]
Hi @smitray,

My bad for the delay 😕🤐😬 and thanks for using `vue-svg-sprite`.

`url` option is a string for the path to an external svg.
Also, you need to use the `symbol` attribute…

I've updated the `README.md` 👍.

**Comment by noudadrichem** [comment]
Hi,

I'm having the same problem with the boilerplate generated with the Vue CLI. I'm using Vue Router and I think this conflicts with the `url:`. I'm using a custom path to my svg sprite but I need my assets folder to resolve that path. The paths is now incorrect (see image)
With custom alias:
http://jmp.sh/uQHcAgn

Normal:
https://jumpshare.com/v/ThGTEUXHDHWXUFIJ7cqo
