### ISSUE TITLE
Generate the SVG Sprite

### ISSUE THREAD

**Issue by aimen-zenasni** [thierrymichel/vue-svg-sprite#24]
Hello,

I have an issue with the generation of the sprite, i can't do that using Gulp or Grunt, do you have any idea to do it with Vue CLI or Webpack only ?

Thanks.

**Comment by thierrymichel** [comment]
Hi @AimenZenasni ,

I've already used this script  (`package.json`): `"svg": "svg-sprite --config svg-sprite.config.json src/assets/svg/./**/*.svg"`
With [svg-sprite](https://www.npmjs.com/package/svg-sprite)

I hope it will help,
Thierry

**Comment by aimen-zenasni** [comment]
Hi @thierrymichel,
Thanks i'm gonna try it!
