### ISSUE TITLE
Path not resolved, not working

### ISSUE THREAD

**Issue by maxiong88** [thierrymichel/vue-svg-sprite#28]
I use it in vue-cli3

`
import SvgSprite from 'vue-svg-sprite';

Vue.use(SvgSprite);
<svg v-svg
     symbol="icon-person"
     size="0 0 24 24"
     role="presentation"
     class="icon--inline"
></svg>
`

After compilation

`<svg role="presentation" class="icon--inline" viewBox="0 0 24 24" width="24" height="24"><use xlink:href="/assets/svg/sprite.svg#icon-person" href="/assets/svg/sprite.svg#icon-person"></use></svg>`

now,  No `file-loader` is used for the value of the href attribute

Should be compiled into

`<svg role="presentation" class="icon--inline" viewBox="0 0 24 24" width="24" height="24"><use xlink:href="/assets/svg/sprite.svg#icon-person" href="/img/sprite.53e2448f.svg#icon-person"></use></svg>`

Do I need to add configuration to `vue.config.js`

**Comment by maxiong88** [comment]
Need to use 'import / require' to import URL

**Comment by zavsievich** [comment]
Addition:
`require('./assets/svg/sprite.svg')`
