### ISSUE TITLE
Uncaught TypeError: r.define Component is not a function

### ISSUE THREAD

**Issue by bogdanfer** [thierrymichel/vue-svg-sprite#32]
added in my view: `Project.vue` 

`import SvgSprite from "vue-svg-sprite";`
`components: { SvgSprite },`
and in the markup:
`<SvgSprite symbol="autorizatie-de-constructie" size="24" />` 

but getting the following error:
`Uncaught TypeError: r.define Component is not a function`

also tried to declare it globally, but still the same. 
any ideas?

**Comment by thierrymichel** [comment]
Hi @bogdanfer,

Thanks for using `vue-svg-sprite`.
Some [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be appreciated!

**Comment by iehowe** [comment]
Hi, this happens if you try to use the Vue 3 plugin with Vue 2. @bogdanfer will need to install version 1.4.3 for Vue 2 support.
