### ISSUE TITLE
Compatibility with IE9+ and edge?

### ISSUE THREAD

**Issue by lahana** [thierrymichel/vue-svg-sprite#4]

**Comment by thierrymichel** [comment]
Hi @lahana,

For IE9+ support, you can use inline SVG (rather than an external source) like this:
```js
import VueSvg from 'vue-svg-sprite';
Vue.use(VueSvg, {
  url: '',
});
```
Or try some polyfill ([read more](https://css-tricks.com/svg-use-external-source/)).

About Edge, do you have a particular problem?

**Comment by lahana** [comment]
I was already going to use this polyfill. You can close the issue...
It worked! Thank you!
