### ISSUE TITLE
Console error in Internet Explorer

### ISSUE THREAD

**Issue by hhjung2013** [thierrymichel/vue-svg-sprite#6]
We use the following markup for our SVG:
`<svg v-svg url="/assets/svg/sprite.svg" symbol="s-xl" width="493.228" height="493.228" viewBox="0 0 493.228 493.228"></svg>`
and IE 11 and Edge log an error in the console:
[Vue warn]: Error in directive svg update hook: "TypeError: Unable to get property '0' of undefined or null reference"

![vue-warn-svg](https://user-images.githubusercontent.com/28895406/38246149-1a99e414-3741-11e8-8840-7dd2e3aaa206.png)

**Comment by thierrymichel** [comment]
Hi @hhjung2013,

Thanks for using `vue-svg-sprite`.
I can not reproduce the issue.
Is it possible to have more informations about versions (Vue, vue-svg-sprite)?
Maybe some repo with the issue (or some jsbin or codepen or …)?
And how to reproduce it? It seems that it happens on `update` but you do not use any binding?

Thanks in advance.

**Comment by ghost** [comment]
@hhjung2013 Hey! Have you used this library with the new vue-cli (3.0.0)? How should webpack be configured? I opened an issue (https://github.com/thierrymichel/vue-svg-sprite/issues/7), but @thierrymichel hasn't seen it yet.
