### ISSUE TITLE
Add empty default

### ISSUE THREAD

**Issue by jpsc** [thierrymichel/vue-svg-sprite#9]
Currently when you create and add a new icon that does not exist on the sprite it breaks the component render. 

How about adding a default empty one when there is no match?
We a can also display a warning to the user on the console.

**Comment by thierrymichel** [comment]
Hi @jpsc, thanks for using `vue-svg-sprite`.

I'm not sure to get the point…
You use `<svg v-svg symbol="missing-icon"></svg>` and it breaks the rendering?
The plugin should not care about the fact that there is, or not, this symbol inside the SVG spritesheet…

**Comment by jpsc** [comment]
@thierrymichel you are right. When I reported it was happening to me. Now I can't reproduce it.
Thanks for the answer anyways.
